using System.Collections.Generic;
using System.IO;
using MonsterBattler.Sim;
using UnityEngine;

namespace MonsterBattler.Game.UI
{
    /// <summary>
    /// Loads the move-category icons (physical starburst / special rings / status waves) from
    /// StreamingAssets/ui/cat_*.png at runtime, cached. Generated by tools (PIL) — no importer setup.
    /// </summary>
    public static class CategoryIcons
    {
        static readonly Dictionary<MoveCategory, Sprite> _cache = new();

        public static Sprite Load(MoveCategory cat)
        {
            if (_cache.TryGetValue(cat, out var cached)) return cached;
            string name = cat switch
            {
                MoveCategory.Physical => "cat_physical",
                MoveCategory.Special => "cat_special",
                _ => "cat_status",
            };
            Sprite sprite = null;
            string path = Path.Combine(Application.streamingAssetsPath, "ui", name + ".png");
            if (File.Exists(path))
            {
                var tex = new Texture2D(2, 2, TextureFormat.RGBA32, false) { filterMode = FilterMode.Bilinear };
                if (tex.LoadImage(File.ReadAllBytes(path)))
                {
                    tex.Apply();
                    sprite = Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), new Vector2(0.5f, 0.5f), 64f);
                }
            }
            _cache[cat] = sprite;
            return sprite;
        }

        /// <summary>Set an Image to the category icon (hides the Image if the sprite is missing).</summary>
        public static void Apply(UnityEngine.UI.Image img, MoveCategory cat)
        {
            if (img == null) return;
            var s = Load(cat);
            img.sprite = s;
            img.enabled = s != null;
        }

        /// <summary>Hex color for category words in rich text — delegates to the pure TypeColors.</summary>
        public static string Hex(MoveCategory cat) => TypeColors.CategoryHex(cat);
    }
}
